apiVersion: app/v1
kind: Deployment
metadata:
  name: static
  namespace: frontend
spec:
  selector:
    matchLables:
      app: static-application
  replicas: 2
  template:
    metadata:
      labels:
        app: static-application
    spec:
      containers:
      - name: static
        ports: 80

  